/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dell
 */
public class AppointmentForm extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentForm
     */
    public AppointmentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAppointmentNumber = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        txtDentistName = new javax.swing.JTextField();
        txtTreatmentType = new javax.swing.JTextField();
        txtAppointmentDate = new javax.swing.JTextField();
        txtAppointmentTime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();

        jTextField3.setText("jTextField1");

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("Appointment Portal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 23, 227, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Appointment Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 116, 165, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 196, 165, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Patient Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 156, 165, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Contact Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 236, 165, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Dentist Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 276, 165, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Treatment Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 316, 165, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText(" Appointment Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 356, 165, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Appointment Time");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 396, 165, -1));
        getContentPane().add(txtAppointmentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 116, 155, -1));
        getContentPane().add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 156, 155, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 196, 155, -1));
        getContentPane().add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 236, 155, -1));
        getContentPane().add(txtDentistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 276, 155, -1));
        getContentPane().add(txtTreatmentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 316, 155, -1));

        txtAppointmentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppointmentDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtAppointmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 356, 155, -1));
        getContentPane().add(txtAppointmentTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 396, 155, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 457, 124, -1));

        btnBack.setText("Back to Menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 457, 115, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, 420, 23));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-blur-hospital-clinic-interior-background_43963-2617.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 430, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    String appointmentNumber = txtAppointmentNumber.getText().trim();
    String patientName = txtPatientName.getText().trim();
    String address = txtAddress.getText().trim();
    String contactNumber = txtContactNumber.getText().trim();
    String dentistName = txtDentistName.getText().trim();
    String treatmentType = txtTreatmentType.getText().trim();
    String appointmentDate = txtAppointmentDate.getText().trim();
    String appointmentTime = txtAppointmentTime.getText().trim();

    // Validation: check nothing is empty
    if (appointmentNumber.isEmpty() || patientName.isEmpty() || address.isEmpty()
            || contactNumber.isEmpty() || dentistName.isEmpty() || treatmentType.isEmpty()
            || appointmentDate.isEmpty() || appointmentTime.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "All fields are required.", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validation: contact number should be digits only
    if (!contactNumber.matches("\\d{9,10}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Contact number must be 9-10 digits.", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Convert date from d/M/yyyy to yyyy-MM-dd for MySQL
    String formattedDate;
    try {
        java.time.format.DateTimeFormatter inputDateFormat = java.time.format.DateTimeFormatter.ofPattern("d/M/yyyy");
        java.time.LocalDate parsedDate = java.time.LocalDate.parse(appointmentDate, inputDateFormat);
        formattedDate = parsedDate.toString(); // yyyy-MM-dd
    } catch (java.time.format.DateTimeParseException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Date must be in dd/mm/yyyy format, e.g. 21/07/2026", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Convert time from h.mm a (e.g. 4.00 pm) to HH:mm:ss for MySQL
    String formattedTime;
    try {
        java.time.format.DateTimeFormatter inputTimeFormat = java.time.format.DateTimeFormatter.ofPattern("h.mm a", java.util.Locale.ENGLISH);
        java.time.LocalTime parsedTime = java.time.LocalTime.parse(appointmentTime.toUpperCase(), inputTimeFormat);
        formattedTime = parsedTime.toString(); // HH:mm
    } catch (java.time.format.DateTimeParseException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Time must be like 4.00 pm", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    model.Appointment appointment = new model.Appointment(appointmentNumber, patientName, address,
            contactNumber, dentistName, treatmentType, formattedDate, formattedTime);

    dao.AppointmentDAO dao = new dao.AppointmentDAO();
    boolean success = dao.addAppointment(appointment);

    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Appointment registered successfully!");
        txtAppointmentNumber.setText("");
        txtPatientName.setText("");
        txtAddress.setText("");
        txtContactNumber.setText("");
        txtDentistName.setText("");
        txtTreatmentType.setText("");
        txtAppointmentDate.setText("");
        txtAppointmentTime.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to save appointment. Check console for details.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

    new MainDashboard().setVisible(true);
    this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtAppointmentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppointmentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppointmentDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentNumber;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtDentistName;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtTreatmentType;
    // End of variables declaration//GEN-END:variables
}
