/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dell
 */
public class BillForm extends javax.swing.JFrame {
    
    private String role = "receptionist"; // default if opened without specifying

    /**
     * Creates new form BillForm
     */
    public BillForm() {
        initComponents();
    }
    
    public BillForm(String role) {
    initComponents();
    this.role = role;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBillSearch = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TREATMENT BILL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 16, 171, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Enter Appointment Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, -1, -1));

        txtBillSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtBillSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 82, 116, -1));

        btnCalculate.setText("Calculate Bill");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 136, -1, -1));

        txtReceipt.setEditable(false);
        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane1.setViewportView(txtReceipt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 193, 247, 253));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 472, -1, -1));

        btnBack.setText("Back to Menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 472, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-blur-hospital-clinic-medical-interior-background_979131-8461.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 330, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBillSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBillSearchActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        
    String appointmentNumber = txtBillSearch.getText().trim();

    if (appointmentNumber.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter an appointment number.", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    dao.AppointmentDAO appointmentDao = new dao.AppointmentDAO();
    model.Appointment appointment = appointmentDao.getAppointmentByNumber(appointmentNumber);

    if (appointment == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No appointment found with that number.", "Not Found", javax.swing.JOptionPane.WARNING_MESSAGE);
        txtReceipt.setText("");
        return;
    }

    service.BillingService billingService = new service.BillingService();
    double consultationFee = billingService.getConsultationFee();
    double treatmentCost = billingService.getTreatmentCost(appointment.getTreatmentType());

    model.Bill bill = new model.Bill(appointmentNumber, consultationFee, treatmentCost);
    String receipt = bill.generateReceipt(appointment);

    txtReceipt.setText(receipt);

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
         if (txtReceipt.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Calculate a bill first before printing.", "Nothing to Print", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    try {
        txtReceipt.print();
    } catch (java.awt.print.PrinterException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Printing failed: " + e.getMessage(), "Print Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
   if ("patient".equalsIgnoreCase(role)) {
        new PatientDashboard().setVisible(true);
    } else {
        new MainDashboard().setVisible(true);
    }
    this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBillSearch;
    private javax.swing.JTextArea txtReceipt;
    // End of variables declaration//GEN-END:variables
}
