/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dell
 */
public class DisplayForm extends javax.swing.JFrame {
    
    private String role = "receptionist"; // default if opened without specifying

    /**
     * Creates new form DisplayForm
     */
    public DisplayForm() {
        initComponents();
        setupEmptyTable();
    }
    
    public DisplayForm(String role) {
    initComponents();
    this.role = role;
    setupEmptyTable();
}
    
    private void setupEmptyTable() {
    javax.swing.table.DefaultTableModel emptyModel = new javax.swing.table.DefaultTableModel(
            new Object[]{"Field", "Value"}, 0) {
        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };
    tblAppointmentDetails.setModel(emptyModel);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lable1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearchNumber = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointmentDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lable1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lable1.setText("Enter Appointment Number");
        getContentPane().add(lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 230, 40));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 98, 120, -1));

        txtSearchNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearchNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 98, 174, -1));

        btnBack.setText("Back to Menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 408, -1, -1));

        tblAppointmentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAppointmentDetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 180, 357, 185));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-blur-hospital-clinic-interior-background_43963-2617.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
                                           
    
    String searchNumber = txtSearchNumber.getText().trim();

    if (searchNumber.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter an appointment number.", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    dao.AppointmentDAO dao = new dao.AppointmentDAO();
    model.Appointment appointment = dao.getAppointmentByNumber(searchNumber);

    javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(
            new Object[]{"Field", "Value"}, 0) {
        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };

    if (appointment != null) {
        tableModel.addRow(new Object[]{"Appointment Number", appointment.getAppointmentNumber()});
        tableModel.addRow(new Object[]{"Patient Name", appointment.getPatientName()});
        tableModel.addRow(new Object[]{"Address", appointment.getAddress()});
        tableModel.addRow(new Object[]{"Contact Number", appointment.getContactNumber()});
        tableModel.addRow(new Object[]{"Dentist", appointment.getDentistName()});
        tableModel.addRow(new Object[]{"Treatment", appointment.getTreatmentType()});
        tableModel.addRow(new Object[]{"Date", appointment.getAppointmentDate()});
        tableModel.addRow(new Object[]{"Time", appointment.getAppointmentTime()});
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No appointment found with that number.", "Not Found", javax.swing.JOptionPane.WARNING_MESSAGE);
    }

    tblAppointmentDetails.setModel(tableModel);


    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchNumberActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
   if ("patient".equalsIgnoreCase(role)) {
        new PatientDashboard().setVisible(true);
    } else {
        new MainDashboard().setVisible(true);
    }
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lable1;
    private javax.swing.JTable tblAppointmentDetails;
    private javax.swing.JTextField txtSearchNumber;
    // End of variables declaration//GEN-END:variables
}
