/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dell
 */
public class PatientDashboard extends javax.swing.JFrame {

    /**
     * Creates new form PatientDashboard
     */
    public PatientDashboard() {
        initComponents();
    }
    
    private String contactNumber;

public PatientDashboard(String contactNumber) {
    initComponents();
    this.contactNumber = contactNumber;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPatientDisplay = new javax.swing.JButton();
        btnPatientBill = new javax.swing.JButton();
        btnPatientLogout = new javax.swing.JButton();
        btnPatientExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("PATIENT DASHBOARD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 20, 231, -1));

        btnPatientDisplay.setText("Display Appointment");
        btnPatientDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatientDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 91, 188, 60));

        btnPatientBill.setText("View Bill");
        btnPatientBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatientBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 169, 188, 60));

        btnPatientLogout.setText("Logout");
        btnPatientLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatientLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 277, 108, 36));

        btnPatientExit.setText("Exit");
        btnPatientExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatientExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 275, 114, 39));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-blur-hospital-clinic-interior-background_43963-2617.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientDisplayActionPerformed
             dao.AppointmentDAO appointmentDao = new dao.AppointmentDAO();
    model.Appointment appointment = appointmentDao.getLatestAppointmentByContact(contactNumber);

    if (appointment != null) {
        String details = "Appointment No: " + appointment.getAppointmentNumber() + "\n"
                + "Patient Name: " + appointment.getPatientName() + "\n"
                + "Address: " + appointment.getAddress() + "\n"
                + "Contact Number: " + appointment.getContactNumber() + "\n"
                + "Dentist: " + appointment.getDentistName() + "\n"
                + "Treatment: " + appointment.getTreatmentType() + "\n"
                + "Date: " + appointment.getAppointmentDate() + "\n"
                + "Time: " + appointment.getAppointmentTime();
        javax.swing.JOptionPane.showMessageDialog(this, details, "Your Appointment", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No appointment found linked to your account. Please contact the clinic.", "Not Found", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnPatientDisplayActionPerformed

    private void btnPatientBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientBillActionPerformed
      dao.AppointmentDAO appointmentDao = new dao.AppointmentDAO();
    model.Appointment appointment = appointmentDao.getLatestAppointmentByContact(contactNumber);

    if (appointment == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No appointment found linked to your account.", "Not Found", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    service.BillingService billingService = new service.BillingService();
    double consultationFee = billingService.getConsultationFee();
    double treatmentCost = billingService.getTreatmentCost(appointment.getTreatmentType());
    model.Bill bill = new model.Bill(appointment.getAppointmentNumber(), consultationFee, treatmentCost);

    javax.swing.JOptionPane.showMessageDialog(this, bill.generateReceipt(appointment), "Your Bill", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnPatientBillActionPerformed

    private void btnPatientLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientLogoutActionPerformed
     new LoginForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnPatientLogoutActionPerformed

    private void btnPatientExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientExitActionPerformed
         int choice = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm Exit", javax.swing.JOptionPane.YES_NO_OPTION);
    if (choice == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnPatientExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPatientBill;
    private javax.swing.JButton btnPatientDisplay;
    private javax.swing.JButton btnPatientExit;
    private javax.swing.JButton btnPatientLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
