/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dell
 */
public class PatientDashboard extends javax.swing.JFrame {

    /**
     * Creates new form PatientDashboard
     */
    public PatientDashboard() {
        initComponents();
    }
    
    private String contactNumber;

public PatientDashboard(String contactNumber) {
    initComponents();
    this.contactNumber = contactNumber;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPatientDisplay = new javax.swing.JButton();
        btnPatientBill = new javax.swing.JButton();
        btnPatientLogout = new javax.swing.JButton();
        btnPatientExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("PATIENT DASHBOARD");

        btnPatientDisplay.setText("Display Appointment");
        btnPatientDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientDisplayActionPerformed(evt);
            }
        });

        btnPatientBill.setText("View Bill");
        btnPatientBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientBillActionPerformed(evt);
            }
        });

        btnPatientLogout.setText("Logout");
        btnPatientLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientLogoutActionPerformed(evt);
            }
        });

        btnPatientExit.setText("Exit");
        btnPatientExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnPatientExit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPatientLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPatientBill, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPatientDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(btnPatientDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPatientBill, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPatientLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPatientExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientDisplayActionPerformed
             dao.AppointmentDAO appointmentDao = new dao.AppointmentDAO();
    model.Appointment appointment = appointmentDao.getLatestAppointmentByContact(contactNumber);

    if (appointment != null) {
        String details = "Appointment No: " + appointment.getAppointmentNumber() + "\n"
                + "Patient Name: " + appointment.getPatientName() + "\n"
                + "Address: " + appointment.getAddress() + "\n"
                + "Contact Number: " + appointment.getContactNumber() + "\n"
                + "Dentist: " + appointment.getDentistName() + "\n"
                + "Treatment: " + appointment.getTreatmentType() + "\n"
                + "Date: " + appointment.getAppointmentDate() + "\n"
                + "Time: " + appointment.getAppointmentTime();
        javax.swing.JOptionPane.showMessageDialog(this, details, "Your Appointment", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No appointment found linked to your account. Please contact the clinic.", "Not Found", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnPatientDisplayActionPerformed

    private void btnPatientBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientBillActionPerformed
      dao.AppointmentDAO appointmentDao = new dao.AppointmentDAO();
    model.Appointment appointment = appointmentDao.getLatestAppointmentByContact(contactNumber);

    if (appointment == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No appointment found linked to your account.", "Not Found", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    service.BillingService billingService = new service.BillingService();
    double consultationFee = billingService.getConsultationFee();
    double treatmentCost = billingService.getTreatmentCost(appointment.getTreatmentType());
    model.Bill bill = new model.Bill(appointment.getAppointmentNumber(), consultationFee, treatmentCost);

    javax.swing.JOptionPane.showMessageDialog(this, bill.generateReceipt(appointment), "Your Bill", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnPatientBillActionPerformed

    private void btnPatientLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientLogoutActionPerformed
     new LoginForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnPatientLogoutActionPerformed

    private void btnPatientExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientExitActionPerformed
         int choice = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm Exit", javax.swing.JOptionPane.YES_NO_OPTION);
    if (choice == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnPatientExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPatientBill;
    private javax.swing.JButton btnPatientDisplay;
    private javax.swing.JButton btnPatientExit;
    private javax.swing.JButton btnPatientLogout;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
